replicaCount: 1
image:
  repository: 10.0.0.103/sre-demo/web
  tag: build-3
  pullPolicy: IfNotPresent
imagePullSecrets: []
service:
  nodePort: 30080
resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 64Mi
readinessProbe:
  path: /
