apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sre-prod
  namespace: argocd
spec:
  project: sre-lab
  source:
    repoURL: https://github.com/VIoletEve/sre-gitops.git
    targetRevision: main
    path: charts/sre-demo
    helm:
      valueFiles:
        - ../../environments/prod-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sre-prod
  syncPolicy:
    automated:
      enabled: false
      prune: true
      selfHeal: false
